#%RAML 0.8
title: BUZZ API
baseUri: http://github.com/buzz

documentation:
  - title: Buzz API
    content: TODO

schemas:
  - buzz.json: !include schemas/buzz.json
  - buzzes: !include schemas/buzzes.json
  
traits:
  - secured: !include traits/auth.raml
  - orderable: !include traits/orderable.raml
  - pageable: !include traits/pageable.raml
  - searchable: !include traits/searchable.raml

resourceTypes:
  - collection-item: !include rtypes/item-collection.raml
  
/buzz:
  get:
    description: Get 
    is: [      
      searchable: {description: "with valid searchable fields", example: "active=true"},
      pageable
      ]
    responses:
      200:
        body:
          application/json:
            schema: buzzes
            example: examples/buzz.example
      400:
        description: "Bad request"
        body:
          text/plain:
            example: "Bad request"
      403:
        description: "Access denied"
        body:
          text/plain:
            example: "Access denied"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  post:
    description: Allow a new user to login and return an authtoken, along with a composite user record
    body:
      application/json:
        schema: buzz.json
        example: examples/buzz.example
    responses:
      201:
        body:
          application/json:
        headers:
          Location:
      400:
        description: "Bad request"
        body:
          text/plain:
            example: "Bad request"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{buzzId}:
    type:
      collection-item:
        exampleItem: !include examples/buzz.example
        schema: buzz.json
